name: travel_mate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_local_notifications: ^13.0.0
  flutter_map: 6.0.1
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_side_menu: ^0.4.0
  fluttertoast: ^8.2.2
  full_screen_image: any
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  latlng: ^1.0.0
  latlong2: ^0.9.0
  location: ^5.0.0
  lottie: ^2.7.0
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  provider: ^6.0.5
  schedulers: ^1.0.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^23.1.44
  timeago: ^3.6.0
  timezone: ^0.9.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/nature.jpg
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/kashmir.jpg
    - assets/images/kodaikanal.jpg
    - assets/images/manali.jpg
    - assets/images/munnar.jpg
    - assets/images/ooty.jpg
    - assets/images/tajMahal.jpg
    - assets/images/user_select.jpg
    - assets/images/aurangabad.jpg
    - assets/images/darjeeling.jpg
    - assets/images/delhi.jpg
    - assets/images/goa.jpg
    - assets/images/hampi.jpg
    - assets/images/hariharfort6.jpg
    - assets/images/idukki.jpg
    - assets/images/jaipur.jpg
    - assets/images/jaisalmer.jpg
    - assets/images/keralabackwater.jpg
    - assets/images/kolkata.jpg
    - assets/images/madhyapradhesh.jpg
    - assets/images/mahabeleshwar.jpg
    - assets/images/mallapuram.jpg
    - assets/images/mumbai.jpg
    - assets/images/mysore.jpg
    - assets/images/pondichery.jpg
    - assets/images/ponmudi.jpg
    - assets/images/punjab.jpg
    - assets/images/rann surat.jpg
    - assets/images/shimla.jpg
    - assets/images/thekkady.jpg
    - assets/images/udaipur.jpg
    - assets/images/uttaraghand.jpg
    - assets/images/vagamon.jpg
    - assets/images/varanasi.jpg
    - assets/images/planTrip.jpg
    - assets/images/planTrip1.jpg
    - assets/images/planTrip2.jpg
    - assets/images/planTrip3.jpg
    - assets/images/planTrip4.jpg
    - assets/images/currentLocation.jpg
    - assets/images/LoginandSignUp.jpg
    - assets/images/logoOfTM.png
    - assets/images/signUp.json
    - assets/images/splash.json
    - assets/images/splashImage.jpg

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
    - family: kanit
      fonts:
        - asset: fonts/Kanit-Medium.ttf
